language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - LARAVEL=5.7.*
    - LARAVEL=5.8.*
    - LARAVEL=dev-master
matrix:
  include:
    - env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=5.7.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=5.8.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^8.0

install:
  - travis_retry composer install --dev 

script: vendor/bin/phpunit --verbose